apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/YOUR_USERNAME/metrics-app'
    targetRevision: HEAD
    path: charts/metrics-app
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true



